apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-mysite"
  labels:
    app: mysite
spec:
  
  replicas: {{ .Values.replicaCount }}
  
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              