apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mysite"
  labels:
    app: mysite
spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000  
  selector:
    app: mysite
